//
//  NewPasswordPresenter.swift
//  savePassword
//
//  Created Danil Ilichev on 12.01.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation
import UIKit

// MARK: View -
protocol NewPasswordViewProtocol: class {
    func addAll()
    func setupConstraints()

}

// MARK: Presenter -
protocol NewPasswordPresenterProtocol: class {
	var view: NewPasswordViewProtocol? { get set }
    var appDepedency: AppDependency? { get set }
    func viewDidLoad()
    func goToAddScreen()
}

class NewPasswordPresenter: NewPasswordPresenterProtocol {

    weak var view: NewPasswordViewProtocol?
    var appDepedency: AppDependency?


    func viewDidLoad() {
        view?.addAll()
        view?.setupConstraints()
        titleTabBar()
    }
    
    func titleTabBar(){
        (self.view as! NewPasswordViewController).title = Localization.TabBar.password
    }
    
    func goToAddScreen(){
        let addPresenter = AddPresenter()
        let addVC = AddViewController(presenter: addPresenter, appDepedency: appDepedency!)
        (view as! NewPasswordViewController).navigationController?.present(addVC, animated: true, completion: nil)
    }
}
