//
//  AddPresenter.swift
//  savePassword
//
//  Created Danil Ilichev on 06.01.2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation
import UIKit

// MARK: View -
protocol AddViewProtocol: class {
    func addAll()
    func setupConstraints()

}

// MARK: Presenter -
protocol AddPresenterProtocol: class {
	var view: AddViewProtocol? { get set }
    var appDepedency: AppDependency? {get set}
    func viewDidLoad()
    func buttonPressedPresenter()
}

class AddPresenter: AddPresenterProtocol {

    weak var view: AddViewProtocol?
    var appDepedency: AppDependency?


    func viewDidLoad() {
        view?.addAll()
        view?.setupConstraints()
    }
    
    func buttonPressedPresenter(){
        let login = (self.view as! AddViewController).loginField.text ?? ""
        let password = (self.view as! AddViewController).passwordField.text ?? ""
        Common.addLoginAndPassword(login: login, password: password, crypt: appDepedency!.cryptService )
        (self.view as! AddViewController).loginField.text = ""
        (self.view as! AddViewController).passwordField.text = ""
        reloadScreens()
    }
    
    func reloadScreens(){
        (self.view as! AddViewController).dismiss(animated: true, completion: nil)
        
        let listNavigationControllers = ((self.view as! AddViewController).presentingViewController as! UITabBarController).viewControllers?[0] as! UINavigationController
        let vc = listNavigationControllers.viewControllers[0] as! ListViewController

        DispatchQueue.global().async {
            self.appDepedency?.cacheService.downloadDataToCash()
            vc.presenter.updateList()
        }
    }
}

